version: '3'

services:

 pi-start-alpine:
  build:
   context: context
   dockerfile: Dockerfile-pitch-alpine
   args:
   - VERSION=${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:pitch-alpine

 pi-start-centos7:
  build:
   context: context
   dockerfile: Dockerfile-pitch-centos7
   args:
   - VERSION=${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:pitch-centos7
  
 pi-start-debian:
  build:
   context: context
   dockerfile: Dockerfile-pitch-debian
   args:
   - VERSION=${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:pitch-debian
