version: '3'

services:

 ma-start-centos7:
  build:
   context: context
   dockerfile: Dockerfile-vtmak-centos7
   args:
   - VERSION=${VTMAK_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:vtmak-centos7
 