version: '3'

services:

 po-start-debian:
  build:
   context: context
   dockerfile: Dockerfile-portico-debian
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:portico-debian

 po-start-centos7:
  build:
   context: context
   dockerfile: Dockerfile-portico-centos7
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}start:portico-centos7
