version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 crc:
  image: ${REPOSITORY}pitch-crc:${PITCH_VERSION}
  volumes:
  - ${PITCH_RTI_HOME}:/usr/local/prti1516e
  environment:
  - DISPLAY=${DISPLAY}

 start1:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - pitchlrc:/usr/local/lrc:nocopy
  - ${PITCH_RTI_HOME}:/usr/local/lrc/code
  environment:
  - LRC_MASTERADDRESS=crc:8989
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 start2:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - pitchlrc:/usr/local/lrc:nocopy
  - ${PITCH_RTI_HOME}:/usr/local/lrc/code
  environment:
  - LRC_MASTERADDRESS=crc:8989
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 lrc:
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}
  volumes:
  - pitchlrc:/usr/local/lrc

volumes:
 pitchlrc:
