version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 crc:
  image: ${REPOSITORY}pitch-crc:${PITCH_VERSION}
  mac_address: ${MAC_ADDRESS}
  volumes:
  - ${PITCH_RTI_HOME}:/usr/local/prti1516e
  environment:
  - DISPLAY=${DISPLAY}

 start:
  image: ${REPOSITORY}start:pitch-alpine
  volumes:
  - ${PITCH_RTI_HOME}:/usr/local/lrc/code
  environment:
  - LRC_MASTERADDRESS=crc:8989
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}

