version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 master:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - porticolrc:/usr/local/lrc:nocopy
  environment:
  - LISTENPORT=8990
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 app1:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - porticolrc:/usr/local/lrc:nocopy
  environment:
  - LRC_MASTERADDRESS=master:8990
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 app2:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - porticolrc:/usr/local/lrc:nocopy
  environment:
  - LRC_MASTERADDRESS=master:8990
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 app3:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - porticolrc:/usr/local/lrc:nocopy
  environment:
  - LRC_MASTERADDRESS=master:8990
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 lrc:
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}
  volumes:
  - porticolrc:/usr/local/lrc

volumes:
 porticolrc: