version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 rtiexec:
  image: ${REPOSITORY}vtmak-rtiexec:${VTMAK_VERSION}
  environment:
  - DISPLAY=${DISPLAY}

 start1:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - vtmaklrc:/usr/local/lrc:nocopy
  environment:
  - LRC_MASTERADDRESS=rtiexec:4000
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 start2:
  image: ${REPOSITORY}start:app-centos7
  entrypoint: /usr/local/lrc/launch.sh
  volumes:
  - vtmaklrc:/usr/local/lrc:nocopy
  environment:
  - LRC_MASTERADDRESS=rtiexec:4000
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - lrc

 lrc:
  image: ${REPOSITORY}lrc:vtmak-${VTMAK_VERSION}
  volumes:
  - vtmaklrc:/usr/local/lrc

volumes:
 vtmaklrc:
