version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 rtiexec:
  image: ${REPOSITORY}vtmak-rtiexec:${VTMAK_VERSION}
  environment:
  - DISPLAY=${DISPLAY}

 start1:
  image: ${REPOSITORY}lrc:vtmak-${VTMAK_VERSION}-centos7
  volumes:
  - myapp:/root/application:nocopy
  environment:
  - LRC_MASTERADDRESS=rtiexec:4000
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - app

 start2:
  image: ${REPOSITORY}lrc:vtmak-${VTMAK_VERSION}-centos7
  volumes:
  - myapp:/root/application:nocopy
  environment:
  - LRC_MASTERADDRESS=rtiexec:4000
  - LRC_ENTRYPOINT=/root/application/start.sh
  - DISPLAY=${DISPLAY}
  depends_on:
  - app

 app:
  image: ${REPOSITORY}start:lrc
  volumes:
  - myapp:/root/application

volumes:
 myapp:
