#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG PITCH_VERSION=skeleton
ARG REPOSITORY=hlacontainers/

#########################
# Create image
#########################
FROM ${REPOSITORY}lrc:pitch-${PITCH_VERSION}-debian-jdk11

# Install application and ensure start script is executable
COPY ./application /root/application
RUN chmod +x /root/application/start.sh

#Set entrypoint
ENV LRC_ENTRYPOINT=/root/application/start.sh
