#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG VTMAK_VERSION=4.5
ARG REPOSITORY=hlacontainers/

#########################
# Create image
#########################
FROM ${REPOSITORY}lrc:vtmak-${VTMAK_VERSION}-centos7

# Install application and ensure start script is executable
COPY ./application /root/application
RUN chmod +x /root/application/start.sh

# Set entrypoint
ENV LRC_ENTRYPOINT=/root/application/start.sh
