#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

FROM centos:7

##############################################################
# Create an image into which the LRC can be mounted.
# The image holds the application, plus the Java run time.
##############################################################

# Install Java
RUN yum update -y \
	&& yum install -y java-1.8.0-openjdk nc iproute \
	&& yum clean all

# Ensure JAVA_HOME is set
ENV JAVA_HOME=/usr/lib/jvm/jre-openjdk

# Install application and ensure start script is executable
COPY ./application /root/application
RUN chmod +x /root/application/start.sh
